# Generated by Django 3.0.7 on 2020-06-29 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('header', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('source', models.TextField()),
                ('claps', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('read_time', models.PositiveIntegerField()),
                ('img_main', models.ImageField(upload_to='imgs/post/%Y/%m/%d')),
                ('img_1', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('img_2', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('img_3', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('img_4', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('img_5', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('img_6', models.ImageField(blank=True, upload_to='imgs/post/%Y/%m/%d')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tags', models.ManyToManyField(to='blog_posts.Tag')),
            ],
        ),
    ]
