# Generated by Django 3.0.7 on 2020-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_6',
        ),
    ]
