# Generated by Django 3.0.7 on 2020-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20200625_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
