# Generated by Django 3.0.7 on 2020-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_post_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.TextField(default='now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
