# Generated by Django 3.0.7 on 2020-06-29 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_auto_20200629_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 16, 56, 53, 767374, tzinfo=utc)),
        ),
    ]
