# Generated by Django 3.0.7 on 2020-06-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_auto_20200626_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='clap',
            new_name='claps',
        ),
    ]
